version: "3.8"

services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - dd-net

  backend:
    image: ${DOCKERHUB_USERNAME}/backend:latest
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/${DB_NAME}?authSource=admin
      PORT: ${BACKEND_PORT}
    networks:
      - dd-net
    expose:
      - "${BACKEND_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- --timeout=3 --tries=1 http://localhost:${BACKEND_PORT}/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  frontend:
    image: ${DOCKERHUB_USERNAME}/frontend:latest
    restart: unless-stopped
    depends_on:_
